CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(50) NOT NULL,
    CLI_CPF VARCHAR(11) NOT NULL,
    CLI_EMAIL VARCHAR(50) NOT NULL,
    CLI_TELEFONE VARCHAR(9) NOT NULL
);

ALTER TABLE CLIENTE 
MODIFY COLUMN CLI_CPF VARCHAR(11) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(50) NOT NULL,
    PRO_DESCRICAO VARCHAR(200),
    PRO_PRECO DOUBLE NOT NULL,
    PRO_QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALU_ID INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL DATE NOT NULL,
    ALU_DATA_DEVOLUCAO DATE NOT NULL,
    ALU_VALOR_TOTAL DOUBLE NOT NULL,
    FK_CLI_ID INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
	ALU_ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRO_ID INT NOT NULL,
    FK_ALU_ID INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
    FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Isabela", "25684563984", "isabela@email.com", "994248574");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Aline", "32847506743", "aline@email.com", "994243845");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Gabriel", "65345698467", "gabriel@email.com", "948573206");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Leonardo", "34865839654", "leo@email.com", "987453689");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Julia", "34562347976", "julia@email.com", "254378476");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Kelli", "98642456396", "kelli@email.com", "937654396");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Guto", "76535976489", "guto@email.com", "987350513");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Ariane", "72484104107", "ariane@email.com", "584378316");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Luiz", "87753690235", "luiz@email.com", "376518935");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Neuza", "28475205710", "neuza@email.com", "285076259");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Deoclides", "38650138505", "del@email.com", "482057643");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
	VALUES ("Dog", "23957683104", "dog@email.com", "294857684");

INSERT INTO PRODUTO (PRO_NOME, PRO_PRECO, PRO_QTD_DISPONIVEL)
	VALUES ("Iphone 18 Pro Max", 589.90, 100);


INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL)
	VALUES ("Lancha Turbo", "Lancha para rio e mar", 2358.75, 5),
			("Notebook Dell Inspiron", "Notebook com processador Intel Core i7, 16GB de RAM, 512GB SSD", 450, 10),
			("Smartphone Samsung Galaxy S21", "Smartphone com tela de 6.2 polegadas, 128GB de armazenamento", 350, 15),
			("TV LG 55 4K", "Smart TV com resolução 4K e HDR", 280, 8),
			("Drone DJI Phantom 4", "Drone com câmera 4K e estabilização de imagem", 300, 55),
			("Câm. Canon EOSI T7", "Câmera DSLR com lente 18-55mm, 24.1MP", 250, 2),
			("Câmera GoPro Hero 9", "Câmera de ação com resolução 5K e resistência a água", 80, 60),
			("Tenda Eventos 5x5m", "Tenda resistente à água e fácil de montar", 200, 4),
			("Microfone Shure SM58", "Microfone para apresentações e shows", 40, 35),
			("Mesa de Som Behringer", "Mesa de som com 16 canais e efeitos integrados", 500, 3),
			("Kit de Iluminação Fotográfica", "Kit com softbox, tripés e lâmpadas de LED", 100, 6);


INSERT INTO ALUGUEL (ALU_DATA_ALUGUEL, ALU_DATA_DEVOLUCAO, ALU_VALOR_TOTAL, FK_CLI_ID)
	VALUES ("2026-10-08", "2026-10-15", 600.89, 2);

INSERT INTO ALUGUEL_PRODUTO (FK_PRO_ID, FK_ALU_ID)
	VALUES (1, 1);

SELECT * FROM PRODUTO;
SELECT * FROM ALUGUEL;
SELECT * FROM CLIENTE;
SELECT * FROM ALUGUEL_PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO FROM PRODUTO;
SELECT 
    PRO_NOME, PRO_DESCRICAO, PRO_PRECO
FROM
    PRODUTO;
    
-- SELECIONAR APENAS OS PRODUTOS COM PRECO > 250
SELECT *
FROM	PRODUTO
WHERE	PRO_PRECO > 250;

-- SELECIONAR APENAS OS PRODUTOS COM ID = 3
SELECT PRO_ID, PRO_NOME
FROM	PRODUTO
WHERE	PRO_ID = 4;

-- SELECIONAR TODOS OS PRODUTOS QUE CONTENHAM NOTEBOOK EM QUALQUER PARTE DO NOME
SELECT *
FROM	PRODUTO
WHERE PRO_NOME LIKE '%NOTEBOOK%';

-- ATUALIZAR A QUANTIDADE DE NOTEBOOK PARA 200
UPDATE PRODUTO
SET PRO_QTD_DISPONIVEL = 200
WHERE	PRO_ID = 4; -- UPDATE TEM QUE TER WHERE

-- ATUALIZAR A DESCRICAO DO NOTEBOOK PARA VAZIO
UPDATE PRODUTO
SET PRO_DESCRICAO = NULL
WHERE PRO_ID = 4; -- UPDATE TEM QUE TER WHERE

-- APAGAR (DELETAR) O NOTEBOOK
DELETE FROM PRODUTO
WHERE PRO_ID = 4; -- DELETE TEM QUE TER WHERE