CREATE DATABASE IF NOT EXISTS BD_APP_MUSICA;
USE BD_APP_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DURACAO TIMESTAMP NOT NULL,
    CAPA BLOB NOT NULL,
    FK_CPF_ARTISTA VARCHAR(11),
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    OUVINTES INT NOT NULL,
    DURACAO TIMESTAMP NOT NULL,
    LETRA VARCHAR(3000) NOT NULL,
    FK_ID_ALBUM INT,
    FK_ID_GENERO INT,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    RITMO VARCHAR(255) NOT NULL,
    ESTILO VARCHAR(255) NOT NULL
);